#!/bin/bash
# “”
rename s/[=#’“”óé’‘…π∆,\$\@\;\(\)\?\!\&\'\[\]]//g *
rename 's/“//g' *
rename 's/”//g' *
rename 's/ //g' *
rename 's/\?//g' *
rename 's/\!//g' *
rename 's/\://g' *
rename 's/\#//g' *
rename  "s/'//g" *
rename  "s/\&//g" *
rename  "s/,//g" *
rename 's/\(//g' *
rename 's/\)//g' *

#rename s/’//g *
#rename s/“//g *
#rename s/”//g *
#rename s/ó//g *
#rename s/é//g *
#rename s/’//g *
#rename s/‘//g *
#rename s/…//g *
#rename s/π//g *
#rename s/∆//g *
#rename s/\;//g *
#rename "s/\'//g" *
#rename 's/\(//g' *
#rename 's/\)//g' *
#rename 's/\!//g' *
#rename 's/;//g' *
#rename 's/\&//g' *
#rename 's/\[|\]//g' *

#rename  's/ |\$|@|,/_/g' *

